/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'bg-blue-50', 'bg-blue-600', 'text-blue-600', 'border-blue-200', 'border-blue-600',
    'bg-emerald-50', 'bg-emerald-600', 'text-emerald-600', 'border-emerald-200', 'border-emerald-600',
    'bg-violet-50', 'bg-violet-600', 'text-violet-600', 'border-violet-200', 'border-violet-600',
    'bg-rose-50', 'bg-rose-600', 'text-rose-600', 'border-rose-200', 'border-rose-600',
    'bg-amber-50', 'bg-amber-600', 'text-amber-600', 'border-amber-200', 'border-amber-600',
    'bg-cyan-50', 'bg-cyan-600', 'text-cyan-600', 'border-cyan-200', 'border-cyan-600',
    'bg-indigo-50', 'bg-indigo-600', 'text-indigo-600', 'border-indigo-200', 'border-indigo-600',
    'bg-orange-50', 'bg-orange-600', 'text-orange-600', 'border-orange-200', 'border-orange-600',
    'bg-blue-500', 'bg-emerald-500', 'bg-violet-500', 'bg-rose-500', 'bg-amber-500',
    'bg-cyan-500', 'bg-indigo-500', 'bg-orange-500',
    'ring-blue-500', 'ring-emerald-500', 'ring-violet-500', 'ring-rose-500',
    'ring-amber-500', 'ring-cyan-500', 'ring-indigo-500', 'ring-orange-500',
  ],
  theme: {
    extend: {
      colors: {
        'bg-primary': 'var(--bg-primary)',
        'bg-secondary': 'var(--bg-secondary)',
        'text-main': 'var(--text-main)',
        'accent': 'var(--accent)',
        'border-glass': 'var(--border-glass)',
        dark: {
          950: '#03040c',
          900: '#050816',
          800: '#0b0e24',
          700: '#141738',
          600: '#1f2352',
          500: '#313780',
        },
        brand: {
          600: '#4f46e5',
          500: '#7c5cff',
          400: '#8b5cf6',
          300: '#a78bfa',
          gradientStart: '#7c5cff',
          gradientEnd: '#4f46e5',
        },
      },
      fontFamily: {
        sans: ['Inter', 'Plus Jakarta Sans', 'system-ui', '-apple-system', 'sans-serif'],
        heading: ['Space Grotesk', 'Plus Jakarta Sans', 'sans-serif'],
        special: ['Sora', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
        serif: ['Merriweather', 'Georgia', 'serif'],
        display: ['Space Grotesk', 'Plus Jakarta Sans', 'sans-serif'],
      },
      animation: {
        'blob': 'blob 7s infinite',
        'blob-slow': 'blob 12s infinite',
        'fade-in': 'fadeIn 0.5s ease-out forwards',
        'fade-in-up': 'fadeInUp 0.6s ease-out forwards',
        'gradient-shift': 'gradientShift 8s ease infinite',
        'float': 'float 6s ease-in-out infinite',
        'float-slow': 'floatSlow 10s ease-in-out infinite',
        'float-delayed': 'float 8s ease-in-out 2s infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'glow-pulse': 'glowPulse 3s ease-in-out infinite',
        'typewriter': 'typewriter 3s steps(30) infinite',
        'blink': 'blink 0.7s step-end infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'counter': 'counter 2s ease-out forwards',
        'slide-up': 'slideUp 0.5s ease-out forwards',
        'slide-down': 'slideDown 0.3s ease-out forwards',
        'slide-in-right': 'slideInRight 0.3s ease-out forwards',
        'spin-slow': 'spin 3s linear infinite',
        'bounce-subtle': 'bounceSubtle 2s ease-in-out infinite',
      },
      keyframes: {
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        gradientShift: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        floatSlow: {
          '0%, 100%': { transform: 'translateY(0) translateX(0)' },
          '25%': { transform: 'translateY(-15px) translateX(10px)' },
          '50%': { transform: 'translateY(-5px) translateX(-5px)' },
          '75%': { transform: 'translateY(-20px) translateX(5px)' },
        },
        glowPulse: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(99, 102, 241, 0.3)' },
          '50%': { boxShadow: '0 0 40px rgba(99, 102, 241, 0.6)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        bounceSubtle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      boxShadow: {
        'glow-brand': '0 0 20px rgba(124, 92, 255, 0.4)',
        'glow-brand-lg': '0 0 40px rgba(124, 92, 255, 0.6)',
        'glow-purple': '0 0 20px rgba(139, 92, 246, 0.4)',
        'glow-blue': '0 0 20px rgba(79, 70, 229, 0.4)',
        'glow-emerald': '0 0 20px rgba(16, 185, 129, 0.4)',
        'glow-rose': '0 0 20px rgba(244, 63, 94, 0.4)',
      },
    },
  },
  plugins: [],
}
