import React from 'react';
import Navbar from '../components/Navbar';
import { Scale, CheckCircle2, UserCheck, Flame, HelpCircle, FileText } from 'lucide-react';
import { motion } from 'framer-motion';

export default function TermsOfService() {
  return (
    <>
      <Navbar />
      <main className="min-h-screen max-w-4xl mx-auto pt-28 pb-16 px-4 sm:px-6 lg:px-8 select-none">
        {/* Header Section */}
        <motion.div
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center space-y-4 mb-12"
        >
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 rounded-full text-xs font-bold uppercase tracking-wider">
            <Scale className="w-3.5 h-3.5" />
            Terms & Guidelines
          </div>
          <h1 className="text-3xl sm:text-4xl font-black font-display tracking-tight text-slate-900 dark:text-white leading-tight">
            Terms of <span className="bg-gradient-to-r from-indigo-400 to-[#ec4899] bg-clip-text text-transparent">Service</span>
          </h1>
          <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed max-w-lg mx-auto font-semibold">
            Last Updated: June 2026. Please read our terms carefully before using the HireCraftt platform.
          </p>
        </motion.div>

        {/* Content Panel */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="bg-white dark:bg-slate-900/60 border border-slate-200 dark:border-white/10 p-6 sm:p-10 rounded-3xl shadow-xl space-y-8 backdrop-blur-xl"
        >
          {/* Section 1 */}
          <div className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <UserCheck className="w-4 h-4 text-indigo-500" />
              1. Acceptance of Terms
            </h2>
            <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed font-semibold">
              By accessing and using HireCraftt, you agree to comply with and be bound by these Terms of Service. If you do not agree, you must refrain from accessing the platform.
            </p>
          </div>

          {/* Section 2 */}
          <div className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-[#ec4899]" />
              2. User Accounts & Security
            </h2>
            <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed font-semibold">
              To utilize the builder and portfolio generator, you must maintain a secure account:
            </p>
            <ul className="list-disc list-inside text-xs text-slate-600 dark:text-slate-400 space-y-1.5 pl-2 font-medium">
              <li>You are responsible for keeping your credentials and password confidential.</li>
              <li>Accounts found distributing malicious resumes, spam, or phishing campaigns will be subject to immediate suspension or banning.</li>
              <li>Premium subscriptions are assigned per user and are not transferable.</li>
            </ul>
          </div>

          {/* Section 3 */}
          <div className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <Flame className="w-4 h-4 text-emerald-500" />
              3. Platform Usage Rules
            </h2>
            <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed font-semibold">
              HireCraftt is designed to boost career growth. Any automated scraping of candidate profiles, portfolios, or resume templates is strictly prohibited.
            </p>
          </div>

          {/* Section 4 */}
          <div className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <FileText className="w-4 h-4 text-sky-500" />
              4. Intellectual Property
            </h2>
            <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed font-semibold">
              All tools, algorithms, 3D assets, console layouts, and core systems are the exclusive intellectual property of HireCraftt. Resumes and portfolios generated by you remain your absolute intellectual property.
            </p>
          </div>

          {/* Section 5 */}
          <div className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <HelpCircle className="w-4 h-4 text-amber-500" />
              5. Limitation of Liability
            </h2>
            <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed font-semibold">
              HireCraftt provides AI recommendations, ATS checking, and career coaching for informational purposes. We do not guarantee employment, salary levels, or hiring success. The platform is provided "as is" without warranties of any kind.
            </p>
          </div>
        </motion.div>
      </main>
    </>
  );
}
